from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml
from jinja2 import Template

# Never deviate from this exact sentence anywhere ULPF references CERT-In/
# SEBI/NCIIPC — compliance is a property of the whole org's posture, not
# something a normalization tool can certify on its own.
SAFE_FRAMING = (
    "ULPF provides technical controls and evidence that support applicable "
    "CERT-In/SEBI/NCIIPC requirements."
)

INCIDENT_REPORT_FIELDS = [
    "incident_timestamp", "systems_affected", "nature_of_incident",
    "remedial_action_taken", "point_of_contact",
]

# ponytail: naive heuristic — one source touching this many distinct ports in the
# flagged set; a real detector would window by time and baseline per source
PORT_SCAN_MIN_PORTS = 5

REPORT_TEMPLATE = Template("""\
# CERT-In Format Incident Report

**{{ safe_framing }}**

| Field | Value |
|---|---|
| Incident Timestamp | {{ incident_timestamp }} |
| Systems Affected | {{ systems_affected }} |
| Nature of Incident | {{ nature_of_incident }} |
| Remedial Action Taken | {{ remedial_action_taken }} |
| Point of Contact | {{ point_of_contact }} |

## Source Events
{% for row in event_rows %}
- `{{ row.id }}` — {{ row.time }} — {{ row.product }} — {{ row.src }} -> {{ row.dst }} \
— disposition: {{ row.disposition }}
{% endfor %}

---
Generated by ULPF at {{ generated_at }} | Retention: {{ retention_days }} days, \
jurisdiction: {{ jurisdiction }} (CERT-In Directions 2022)
""", trim_blocks=True)  # no blank line between event rows


def load_profile(name: str = "cert_in") -> dict:
    path = Path(__file__).parent / "profiles" / f"{name}.yaml"
    return yaml.safe_load(path.read_text())


def _utc(epoch_ms: int | None) -> str:
    if epoch_ms is None:
        return "time unknown"
    return datetime.fromtimestamp(epoch_ms / 1000, timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _ep(event: dict, side: str) -> dict:
    """Network Activity carries endpoints top-level; a Detection Finding (IDS alert) in evidences."""
    return event.get(side) or (event.get("evidences") or [{}])[0].get(side) or {}


def _endpoint(event: dict, side: str) -> str:
    ep = _ep(event, side)
    return f"{ep.get('ip', 'n/a')}:{ep['port']}" if "port" in ep else ep.get("ip", "n/a")


def generate_report(flagged_events: list[dict], point_of_contact: str = "SOC Duty Officer") -> str:
    """Every field except the point of contact is derived from the flagged OCSF
    events themselves — event time, targets, dispositions, and the reporting device."""
    profile = load_profile()
    events = sorted(flagged_events, key=lambda e: e.get("time", 0))

    times = [e["time"] for e in events if "time" in e]
    if not times:
        incident_timestamp = "unknown (source logs carried no parseable timestamp)"
    elif times[0] == times[-1]:
        incident_timestamp = _utc(times[0])
    else:
        incident_timestamp = f"{_utc(times[0])} to {_utc(times[-1])}"

    dispositions = Counter(e.get("disposition", "Unknown") for e in events)
    ports_by_src: dict[str, set] = defaultdict(set)
    for e in events:
        port = _ep(e, "dst_endpoint").get("port")
        ports_by_src[_ep(e, "src_endpoint").get("ip", "unknown")].update([port] if port is not None else [])
    all_ports = sorted(set().union(*ports_by_src.values()))
    nature = (
        f"{len(events)} event(s) ("
        + ", ".join(f"{n} {d}" for d, n in sorted(dispositions.items()))
        + f") from {', '.join(sorted(ports_by_src))} to port(s) {', '.join(map(str, all_ports)) or 'n/a'}"
    )
    scanners = sorted(src for src, ports in ports_by_src.items() if len(ports) >= PORT_SCAN_MIN_PORTS)
    if scanners:
        nature += f"; {', '.join(scanners)} probed {PORT_SCAN_MIN_PORTS}+ distinct ports, consistent with port scanning"

    denied = [e for e in events if e.get("disposition") == "Denied"]
    remedial = []
    if denied:
        devices = sorted({e.get("metadata", {}).get("product", {}).get("name", "unknown") for e in denied})
        remedial.append(f"{len(denied)} event(s) blocked at the perimeter by {', '.join(devices)}")
    if len(denied) < len(events):
        remedial.append(f"{len(events) - len(denied)} event(s) not blocked by the device, pending SOC review")

    return REPORT_TEMPLATE.render(
        safe_framing=SAFE_FRAMING,
        incident_timestamp=incident_timestamp,
        systems_affected=", ".join(sorted({_ep(e, "dst_endpoint").get("ip", "unknown") for e in events})),
        nature_of_incident=nature,
        remedial_action_taken="; ".join(remedial) or "none recorded",
        point_of_contact=point_of_contact,
        event_rows=[
            {
                "id": e.get("ulpf", {}).get("raw_event_id", "n/a"), "time": _utc(e.get("time")),
                "product": e.get("metadata", {}).get("product", {}).get("name", "unknown"),
                "src": _endpoint(e, "src_endpoint"), "dst": _endpoint(e, "dst_endpoint"),
                "disposition": e.get("disposition", "Unknown"),
            }
            for e in events
        ],
        generated_at=_utc(int(datetime.now(timezone.utc).timestamp() * 1000)),
        retention_days=profile["retention_days"],
        jurisdiction=profile["jurisdiction"],
    )


def demo():
    def scan_event(i: int, port: int, disposition: str = "Denied") -> dict:
        return {
            "class_uid": 4001, "disposition": disposition,
            "time": 1788099301000 + i * 1000,  # 2026-08-30 14:15:01 UTC onward
            "src_endpoint": {"ip": "203.0.113.44", "port": 40100 + i},
            "dst_endpoint": {"ip": "172.20.1.8", "port": port},
            "metadata": {"product": {"name": "PAN-OS"}},
            "ulpf": {"raw_event_id": f"evt_scan{i}"},
        }

    report = generate_report([scan_event(i, p) for i, p in enumerate([21, 23, 135, 445, 1433])])
    assert SAFE_FRAMING in report
    assert "| Incident Timestamp | 2026-08-30 14:15:01 UTC to 2026-08-30 14:15:05 UTC |" in report
    assert "| Systems Affected | 172.20.1.8 |" in report
    assert "5 Denied" in report and "consistent with port scanning" in report
    assert "5 event(s) blocked at the perimeter by PAN-OS" in report
    assert "evt_scan0" in report and "quarantined" not in report

    mixed = generate_report([scan_event(0, 443, "Allowed"), {"disposition": "Denied", "ulpf": {"raw_event_id": "evt_bare"}}])
    assert "1 event(s) not blocked by the device, pending SOC review" in mixed
    assert "port scanning" not in mixed and "evt_bare" in mixed and "time unknown" in mixed

    ids_alert = {
        "class_uid": 2004, "disposition": "Detected", "time": 1788099302123,
        "evidences": [{"src_endpoint": {"ip": "203.0.113.44", "port": 40100},
                       "dst_endpoint": {"ip": "172.20.1.8", "port": 22}}],
        "metadata": {"product": {"name": "Suricata"}}, "ulpf": {"raw_event_id": "evt_ids"},
    }
    ids_report = generate_report([ids_alert])
    assert "| Systems Affected | 172.20.1.8 |" in ids_report and "203.0.113.44:40100 -> 172.20.1.8:22" in ids_report
    assert "1 Detected" in ids_report and "pending SOC review" in ids_report
    print("compliance report_generator demo: OK")
    print(report)


if __name__ == "__main__":
    demo()
