from datetime import datetime, timezone
from pathlib import Path

import yaml
from jinja2 import Template

# Never deviate from this exact sentence anywhere ULPF references CERT-In/
# SEBI/NCIIPC — compliance is a property of the whole org's posture, not
# something a normalization tool can certify on its own.
SAFE_FRAMING = (
    "ULPF provides technical controls and evidence that support applicable "
    "CERT-In/SEBI/NCIIPC requirements."
)

INCIDENT_REPORT_FIELDS = [
    "incident_timestamp", "systems_affected", "nature_of_incident",
    "remedial_action_taken", "point_of_contact",
]

REPORT_TEMPLATE = Template("""\
# CERT-In Format Incident Report

**{{ safe_framing }}**

| Field | Value |
|---|---|
| Incident Timestamp | {{ incident_timestamp }} |
| Systems Affected | {{ systems_affected }} |
| Nature of Incident | {{ nature_of_incident }} |
| Remedial Action Taken | {{ remedial_action_taken }} |
| Point of Contact | {{ point_of_contact }} |

## Source Events
{% for event in source_events %}
- `{{ event.ulpf.raw_event_id }}` — {{ event.metadata.product.name }} — \
{{ event.src_endpoint.ip | default('n/a') }} -> \
{{ event.dst_endpoint.ip | default('n/a') }}:{{ event.dst_endpoint.port | default('n/a') }} \
— disposition: {{ event.disposition }}
{% endfor %}

---
Generated by ULPF | Retention: {{ retention_days }} days, jurisdiction: {{ jurisdiction }} \
(CERT-In Directions 2022)
""")


def load_profile(name: str = "cert_in") -> dict:
    path = Path(__file__).parent / "profiles" / f"{name}.yaml"
    return yaml.safe_load(path.read_text())


def generate_report(flagged_events: list[dict], point_of_contact: str = "SOC Duty Officer") -> str:
    profile = load_profile()
    systems = sorted({
        e.get("dst_endpoint", {}).get("ip", "unknown") for e in flagged_events
    })
    return REPORT_TEMPLATE.render(
        safe_framing=SAFE_FRAMING,
        incident_timestamp=datetime.now(timezone.utc).isoformat(),
        systems_affected=", ".join(systems) or "unknown",
        nature_of_incident=(
            f"{len(flagged_events)} flagged network activity event(s) — "
            "schema drift / anomalous pattern"
        ),
        remedial_action_taken="Event(s) quarantined by ULPF Schema Drift Firewall pending SOC review.",
        point_of_contact=point_of_contact,
        source_events=flagged_events,
        retention_days=profile["retention_days"],
        jurisdiction=profile["jurisdiction"],
    )


def demo():
    sample_event = {
        "class_uid": 4001, "disposition": "Denied",
        "src_endpoint": {"ip": "10.10.1.20"},
        "dst_endpoint": {"ip": "172.16.1.50", "port": 443},
        "metadata": {"product": {"name": "Cisco ASA"}},
        "ulpf": {"raw_event_id": "evt_893823"},
    }
    report = generate_report([sample_event])
    assert SAFE_FRAMING in report
    assert "172.16.1.50" in report
    assert "evt_893823" in report
    assert "Cisco ASA" in report
    assert "Incident Timestamp" in report and "Point of Contact" in report
    print("compliance report_generator demo: OK")
    print(report)


if __name__ == "__main__":
    demo()
